"""Create promocodes table

Revision ID: 384a9ffab6e8
Revises: 
Create Date: 2025-08-23 20:57:21.924447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '384a9ffab6e8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guilds_settings',
    sa.Column('shop_events_channel_id', sa.Integer(), nullable=True),
    sa.Column('reward_delay', sa.Interval(), nullable=False),
    sa.Column('reward_cost', sa.Integer(), nullable=False),
    sa.Column('is_rewards_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_shop_enabled', sa.Boolean(), nullable=False),
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id')
    )
    op.create_index(op.f('ix_guilds_settings_id'), 'guilds_settings', ['id'], unique=False)
    op.create_table('promocodes',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('max_usages', sa.Integer(), nullable=True),
    sa.Column('usages_count', sa.Integer(), nullable=False),
    sa.Column('bonus', sa.Integer(), nullable=False),
    sa.Column('is_infinite_usages', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promocodes_id'), 'promocodes', ['id'], unique=False)
    op.create_table('shops_items',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('remaining', sa.Integer(), nullable=False),
    sa.Column('is_for_sell', sa.Boolean(), nullable=False),
    sa.Column('is_infinite', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id')
    )
    op.create_index(op.f('ix_shops_items_id'), 'shops_items', ['id'], unique=False)
    op.create_table('users',
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('discord_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('last_reward_date', sa.DateTime(), nullable=False),
    sa.Column('used_promocode_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['used_promocode_id'], ['promocodes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discord_id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_shops_items_id'), table_name='shops_items')
    op.drop_table('shops_items')
    op.drop_index(op.f('ix_promocodes_id'), table_name='promocodes')
    op.drop_table('promocodes')
    op.drop_index(op.f('ix_guilds_settings_id'), table_name='guilds_settings')
    op.drop_table('guilds_settings')
    # ### end Alembic commands ###
