"""fix

Revision ID: 87bd172918d0
Revises: b11594d6fc2b
Create Date: 2025-08-22 17:18:55.638506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87bd172918d0'
down_revision: Union[str, Sequence[str], None] = 'b11594d6fc2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shops_items',
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('remaining', sa.Integer(), nullable=False),
    sa.Column('is_for_sell', sa.Boolean(), nullable=False),
    sa.Column('is_infinite', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id')
    )
    op.create_index(op.f('ix_shops_items_id'), 'shops_items', ['id'], unique=False)
    op.add_column('guilds_settings', sa.Column('shop_events_channel_id', sa.Integer(), nullable=True))
    op.add_column('guilds_settings', sa.Column('is_shop_enabled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guilds_settings', 'is_shop_enabled')
    op.drop_column('guilds_settings', 'shop_events_channel_id')
    op.drop_index(op.f('ix_shops_items_id'), table_name='shops_items')
    op.drop_table('shops_items')
    # ### end Alembic commands ###
