"""fix

Revision ID: b11594d6fc2b
Revises: 5648133f0c39
Create Date: 2025-08-16 20:27:43.524338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b11594d6fc2b'
down_revision: Union[str, Sequence[str], None] = '5648133f0c39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guilds_settings', sa.Column('reward_delay', sa.Interval(), nullable=False))
    op.add_column('guilds_settings', sa.Column('reward_cost', sa.Integer(), nullable=False))
    op.add_column('guilds_settings', sa.Column('is_rewards_enabled', sa.Boolean(), nullable=False))
    op.drop_column('guilds_settings', 'daily_reward_cost')
    op.drop_column('guilds_settings', 'is_daily_rewards_enabled')
    op.drop_column('guilds_settings', 'daily_reward_delay')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guilds_settings', sa.Column('daily_reward_delay', sa.DATETIME(), nullable=False))
    op.add_column('guilds_settings', sa.Column('is_daily_rewards_enabled', sa.BOOLEAN(), nullable=False))
    op.add_column('guilds_settings', sa.Column('daily_reward_cost', sa.INTEGER(), nullable=False))
    op.drop_column('guilds_settings', 'is_rewards_enabled')
    op.drop_column('guilds_settings', 'reward_cost')
    op.drop_column('guilds_settings', 'reward_delay')
    # ### end Alembic commands ###
